name: Build image
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup docker buildx
      uses: crazy-max/ghaction-docker-buildx@v1
    - name: Build image
      run: |
        docker buildx build . \
          --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_USER_TOKEN }} \
          --output "type=image,push=false" \
          --platform linux/arm/v7 \
          --tag vlkoti/raspberrypi3-homeassistant:latest
    - name: Push image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker login -u vlkoti -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push vlkoti/raspberrypi3-homeassistant:latest
